theme: jekyll-theme-minimal
title: Econometría Espacial
description: En este repositorio se encuentra el material del curso de Econometría Espacial del PhD/Maestría en Economía de la Universidad EAFIT (Medellín-Colombia)